version: '3'
services:
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/init.js:ro